version: '3'

services:
  app:
    build: .
    container_name: imersao_node
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    entrypoint: "npm start"
